### ISSUE TITLE
Hints don't appear after update to version 61

### ISSUE THREAD

**Issue by Shamaoke** [amedama41/vvimpulation#1]
After the browser update to version 61, hints have stopped to appear when pressing the corresponding keys.

The console contains the following error:

    Change mode error: rectList.filter is not a function (moz-extension://f18d1a33-ce23-41cc-b58f-8256fa037f7b/content_scripts/hint_mode.js:573)

Other VV functions seem working fine.

_Linux (Arch); FF 61; VV 1.3_

**Comment by amedama41** [comment]
Fixed the issue on version 1.4. Please upgrade VVimpulation.
