### ISSUE TITLE
Caret mode in text fields

### ISSUE THREAD

**Issue by spigelli** [amedama41/vvimpulation#3]
Caret mode seems to be broken. While in text fields if you Ctr+[ out of insert mode and Ctrl+V into caret mode, it still types. It would be nice to use the same vim navigation in our text fields (w, B, e, etc.)

**Comment by amedama41** [comment]
Maybe this is from Firefox bug.

**Comment by amedama41** [comment]
Thank you for your report.
This issue happens due to Firefox bug probably. I will add a workaround into the next release.

> It would be nice to use the same vim navigation in our text fields (w, B, e, etc.)

The feature is useful, but I don't plan to support the feature yet. 
Alternatively, [wasavi](https://github.com/akahuku/wasavi) may help.

**Comment by spigelli** [comment]
> Alternatively, [wasavi](https://github.com/akahuku/wasavi) may help.
Thanks!
